// Code generated by "stringer -type VitoState,CommandType"; DO NOT EDIT.

package vogo

import "strconv"

const _VitoState_name = "unknownresetresetAckresetP300resetP300AckidlesendKwStartsendKwrecvKwswP300waitAckwaitsendP300sendP300AckrecvP300recvP300AckrecvP300Nak"

var _VitoState_index = [...]uint8{0, 7, 12, 20, 29, 41, 45, 56, 62, 68, 74, 81, 85, 93, 104, 112, 123, 134}

func (i VitoState) String() string {
	if i >= VitoState(len(_VitoState_index)-1) {
		return "VitoState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VitoState_name[_VitoState_index[i]:_VitoState_index[i+1]]
}

const _CommandType_name = "nopp300ReadDatap300WriteDatap300FunctionCallphysicalKmbusRAMReadphysicalKmBusEepromReadphysicalPortWritephysicalPortReadphysicalBeWritephysicalBeReadeepromWriteeepromReadphysicalXramWritevirtualWritephysicalXramReadvirtualReadphysicalWritephysicalReadkwWritekwRead"

var _CommandType_map = map[CommandType]string{
	0:   _CommandType_name[0:3],
	1:   _CommandType_name[3:15],
	2:   _CommandType_name[15:28],
	7:   _CommandType_name[28:44],
	51:  _CommandType_name[44:64],
	67:  _CommandType_name[64:87],
	109: _CommandType_name[87:104],
	110: _CommandType_name[104:120],
	157: _CommandType_name[120:135],
	158: _CommandType_name[135:149],
	173: _CommandType_name[149:160],
	174: _CommandType_name[160:170],
	195: _CommandType_name[170:187],
	196: _CommandType_name[187:199],
	197: _CommandType_name[199:215],
	199: _CommandType_name[215:226],
	200: _CommandType_name[226:239],
	203: _CommandType_name[239:251],
	244: _CommandType_name[251:258],
	247: _CommandType_name[258:264],
}

func (i CommandType) String() string {
	if str, ok := _CommandType_map[i]; ok {
		return str
	}
	return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
}
