// Code generated by "stringer -type VitoState,CommandType"; DO NOT EDIT.

package vogo

import "strconv"

const _VitoState_name = "unknownresetresetAckresetP300resetP300AckidlesendKwStartsendKwrecvKwswP300waitAckwaitsendP300sendP300AckrecvP300recvP300AckrecvP300Nak"

var _VitoState_index = [...]uint8{0, 7, 12, 20, 29, 41, 45, 56, 62, 68, 74, 81, 85, 93, 104, 112, 123, 134}

func (i VitoState) String() string {
	if i >= VitoState(len(_VitoState_index)-1) {
		return "VitoState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VitoState_name[_VitoState_index[i]:_VitoState_index[i+1]]
}

const _CommandType_name = "p300ReadDatap300WriteDatap300FunctionCallphysicalKmbusRAMReadphysicalKmBusEepromReadphysicalPortWritephysicalPortReadphysicalBeWritephysicalBeReadeepromWriteeepromReadphysicalXramWritevirtualWritephysicalXramReadvirtualReadphysicalWritephysicalReadkwWritekwRead"

var _CommandType_map = map[CommandType]string{
	1:   _CommandType_name[0:12],
	2:   _CommandType_name[12:25],
	7:   _CommandType_name[25:41],
	51:  _CommandType_name[41:61],
	67:  _CommandType_name[61:84],
	109: _CommandType_name[84:101],
	110: _CommandType_name[101:117],
	157: _CommandType_name[117:132],
	158: _CommandType_name[132:146],
	173: _CommandType_name[146:157],
	174: _CommandType_name[157:167],
	195: _CommandType_name[167:184],
	196: _CommandType_name[184:196],
	197: _CommandType_name[196:212],
	199: _CommandType_name[212:223],
	200: _CommandType_name[223:236],
	203: _CommandType_name[236:248],
	244: _CommandType_name[248:255],
	247: _CommandType_name[255:261],
}

func (i CommandType) String() string {
	if str, ok := _CommandType_map[i]; ok {
		return str
	}
	return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
}
