// Code generated by "stringer -type=VitoState"; DO NOT EDIT.

package optolink

import "strconv"

const _VitoState_name = "unknownresetresetAckidlesendKwStartsendKwrecvKwswP300waitAckwaitsendP300sendP300AckrecvP300recvP300Ack"

var _VitoState_index = [...]uint8{0, 7, 12, 20, 24, 35, 41, 47, 53, 60, 64, 72, 83, 91, 102}

func (i VitoState) String() string {
	if i >= VitoState(len(_VitoState_index)-1) {
		return "VitoState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VitoState_name[_VitoState_index[i]:_VitoState_index[i+1]]
}
